export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL";

export const DETAILS_ORDER_REQUEST = "DETAILS_ORDER_REQUEST";
export const DETAILS_ORDER_SUCCESS = "DETAILS_ORDER_SUCCESS";
export const DETAILS_ORDER_FAIL = "DETAILS_ORDER_FAIL";

export const PAY_ORDER_REQUEST = "PAY_ORDER_REQUEST";
export const PAY_ORDER_SUCCESS = "PAY_ORDER_SUCCESS";
export const PAY_ORDER_FAIL = "PAY_ORDER_FAIL";
export const PAY_ORDER_RESET = "PAY_ORDER_RESET";

export const DELIVERED_ORDER_REQUEST = "DELIVERED_ORDER_REQUEST";
export const DELIVERED_ORDER_SUCCESS = "DELIVERED_ORDER_SUCCESS";
export const DELIVERED_ORDER_FAIL = "DELIVERED_ORDER_FAIL";
export const DELIVERED_ORDER_RESET = "DELIVERED_ORDER_RESET";

export const LIST_MY_ORDER_REQUEST = "LIST_MY_ORDER_REQUEST";
export const LIST_MY_ORDER_SUCCESS = "LIST_MY_ORDER_SUCCESS";
export const LIST_MY_ORDER_FAIL = "LIST_MY_ORDER_FAIL";
export const LIST_MY_ORDER_RESET = "LIST_MY_ORDER_RESET";

export const LIST_ORDER_TO_ADMIN_REQUEST = "LIST_ORDER_TO_ADMIN_REQUEST";
export const LIST_ORDER_TO_ADMIN_SUCCESS = "LIST_ORDER_TO_ADMIN_SUCCESS";
export const LIST_ORDER_TO_ADMIN_FAIL = "LIST_ORDER_TO_ADMIN_FAIL";
export const LIST_ORDER_TO_ADMIN_RESET = "LIST_ORDER_TO_ADMIN_RESET";
